version: '3.8'

services:
  postgres_db:
    image: postgres:16 # Use a specific version of the official Postgres image
    container_name: products-db
    restart: always
    environment:
      POSTGRES_USER: user # The PostgreSQL user (role) to create
      POSTGRES_PASSWORD: user # The password for the user
      POSTGRES_DB: products-db # The initial database to create
    volumes:
      - postgres_data:/var/lib/postgresql/data # Mount a volume for data persistence
    ports:
      - "5438:5432" # Map port 5432 on the host to port 5432 in the container

  redis:
    image: redis:latest # Use the latest official Redis image
    container_name: redis-db
    restart: always
    ports:
      - "6379:6379" # Map port 6379 on the host to port 6379 in the container

volumes:
  postgres_data: